paths:
    data: data
    static: public
    uploads: public/uploads
_editables:
    content:
        blockquote: true
        bold: true
        format: p h2 h3 h4
        italic: true
        strike: true
        subscript: true
        superscript: true
        underline: true
        link: true
        bulletedlist: true
        indent: true
        numberedlist: true
        outdent: true
        code: true
        embed: true
        horizontalrule: true
        image: true
        table: true
        undo: true
        redo: true
        removeformat: true
        copyformatting: true
        styles: /css/editor.css
        left: align-left
        center: align-center
        right: align-right
        justify: align-justify
        image_size_attributes: true
        snippet: true
collections_config:
    data:
        path: data
        disable_add: true
        disable_add_folder: true
    posts:
        path: src/content/blog
        parser: front-matter
        output: true
        url: "/blog/[slug]/"
        _enabled_editors:
            - content
            - visual
        add_options:
            - name: Add New Post
              schema: default
              icon: post_add
        schemas:
            default:
                name: New Post
                path: schemas/post.mdx
        create:
            path: "[relative_base_path]/{title|slugify}.mdx"
        _inputs:
            title:
                options:
                    empty_type: string
            image:
                options:
                    empty_type: string
            image_alt:
                options:
                    empty_type: string
            author:
                options:
                empty_type: string
            categories:
                type: array
                options:
                    allow_create: true
                    empty_type: null
            tags:
                type: array
                options:
                    allow_create: true
                    empty_type: null
    pages:
        path: src/content/pages
        url: "/[slug]/"
        output: true
        icon: wysiwyg
        _enabled_editors:
            - visual
        schemas:
            default:
                name: New Page
                path: schemas/page.md
                new_preview_url: "/"
            paginated_collection:
                path: schemas/paginated-collection.md
        _inputs:
            content_blocks:
                empty_type: array
        filter:
            base: strict
    products:
        path: src/content/products
        output: true
        url: "/product/[slug]/"
        _enabled_editors:
            - content
            - visual
        add_options:
            - name: Add New Product
              schema: default
              icon: post_add
        schemas:
            default:
                name: New Product
                path: schemas/product.md
        _inputs:
            tabbed_content:
                empty_type: array
collection_groups:
    - heading: Pages
      collections:
          - pages
    - heading: Blogging
      collections:
          - posts
    - heading: Products
      collections:
          - products
    - heading: Data
      collections:
          - data

_inputs:
    markdown_content:
        type: markdown
        options:
            blockquote: true
            bold: true
            format: p h1 h2 h3 h4
            italic: true
            strike: true
            subscript: true
            superscript: true
            underline: true
            link: true
            bulletedlist: true
            numberedlist: true
            table: true
            code: true
            embed: true
            horizontalrule: true
            image: true
            undo: true
            redo: true
            removeformat: true
            copyformatting: true
    image_path:
        type: image
        options:
            paths:
                static: "."
                uploads: src/assets/uploads
    alt_text:
        label: Image Alt Text
        type: textarea
        hidden: "!image_path"
    icon:
        type: select
        options:
        values: data.icons
    layout:
        hidden: true
    date:
        instance_value: NOW
    published_date:
        instance_value: NOW
    title_suffix:
        comment: Added at the end of the title and highlighted in a different color
    page_size:
        type: number
        comment: The number of collection items to list per page
    social:
        options:
            preview:
                icon: link
    links:
        options:
            preview:
                icon: link
    items:
        options:
            preview:
                icon: link
    pinned:
        type: switch
    is_featured:
        type: switch
    price:
        type: number
    rating:
        type: number
    component_id:
        comment: Leave blank if not needed
    logo_url:
        comment: Link for the logo in the top left of the footer
    copyright:
        comment: Automatically prefixed with the current year
    is_active:
        type: switch
    primary:
        type: switch
    page_description:
        comment: Defaults to the description set in the Site SEO data file
    favicon_icon:
        type: image
        comment: For the shortcut icon meta tag
    favicon_image:
        type: image
        comment: For the icon meta tag
    canonical_url:
        comment: Defaults to the pages url
    featured_image:
        comment: Defaults to the image set in the Site SEO data file
        type: image
        options:
            paths:
                static: "."
                uploads: src/assets/uploads
    featured_image_alt:
        label: Featured Image Alt Text
        type: textarea
        hidden: "!featured_image"
    open_graph_type:
        comment: Defaults to the type 'website'
    author_twitter_handle:
        comment: Defaults to the twitter site value set in the Site SEO data file
    no_index:
        type: checkbox
        comment: When selected this removes the page from your sitemap and adds the noindex
            robots meta tag

data_config:
    icons:
        path: data/icons.json
generator:
    metadata:
        markdown: markdown-it
        markdown-it:
            html: true
            linkify: false
            breaks: true
_snippets_imports:
    mdx: true
_snippets:
    button:
        template: mdx_component
        inline: false
        preview:
            text: Button
        definitions:
            component_name: SnippetButton
            named_args:
                - editor_key: link
                  source_key: link
                  type: string
                - editor_key: text
                  source_key: text
                  type: string

_structures:
    features:
        values:
            - value:
                  item:
                  isActive:
