# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Testimonials Carousel
  description: Testimonials Carousel
  icon: "bolt"
  tags: ["testimonials", "carousel"]

# Defines the structure of this component, as well as the default values
blueprint:
  component_id:
  heading: "Testimonials"
  content_html: "Explore the whole collection of open-source web components and elements built with the utility classes from Tailwind"
  testimonials:
    - image:
      name:
      position:
      description:

preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  testimonials:
    type: array
