# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Content Heading Description
  description: Content Heading Description
  icon: "bolt"
  tags: ["content", "heading", "description", "2 cols"]

# Defines the structure of this component, as well as the default values
blueprint:
  component_id:
  heading: "Powering innovation at 200,000+ companies worldwide"
  content_left_html: "We are strategists, designers and developers. Innovators and problem solvers. Small enough to be simple and quick, but big enough to deliver the scope you want at the pace you need."
  url: "#"
  link_text: "Learn more"
  content_right_html: "We are strategists, designers and developers. Innovators and problem solvers. Small enough to be simple and quick, but big enough to deliver the scope you want at the pace you need."
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
