# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Features Icon and Link
  description: Features Icon and Link
  icon: "bolt"
  tags: ["features", "link", "icon"]

# Defines the structure of this component, as well as the default values
blueprint:
  component_id:
  heading: "The most trusted cryptocurrency platform"
  content_textarea: "Here are a few reasons why you should choose Flowbite"
  list:
    - icon_image:
      title:
      description:
      link_text:
      link:

preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  list:
    type: array
