# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Newsletter
  description: Newsletter
  icon: "bolt"
  tags: ["newsletter"]

# Defines the structure of this component, as well as the default values
blueprint:
  component_id:
  heading: "Sign up for our newsletter"
  content_html: "Stay up to date with the roadmap progress, announcements and exclusive discounts feel free to sign up with youremail."
  footer_html: "We respect your privacy. Unsubscribe at any time."

preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
