# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Features Comparison Tables
  description: Features Comparison Tables
  icon: "bolt"
  tags: ["features", "comparison", "tables"]

# Defines the structure of this component, as well as the default values
blueprint:
  component_id:
  heading: "The most trusted cryptocurrency platform"
  cta_text: "Get started"
  cta_link: "#"
  items:
    - text:

preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  items:
    type: array
    empty_type: array
