# Metadata about this component, to be used in the CMS
spec:
    structures:
        - content_blocks
    label: Team 2 Cols
    description: Team 2 Cols
    icon: "bolt"
    tags: ["team"]

# Defines the structure of this component, as well as the default values
blueprint:
    component_id:
    heading: "Our Team"
    content_html: "Explore the whole collection of open-source web components and elements built with the utility classes from Tailwind"
    team_members:
        - image_path:
          name:
          position:
          description:
          socials:
              - url:
                icon:
          order_number:

preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    team_members:
        type: array
    icon:
        type: select
        options:
            values:
                - Facebook
                - Twitter
                - Instagram
                - LinkedIn
                - GitHub
                - YouTube
                - TikTok
