# Metadata about this component, to be used in the CMS
spec:
    structures:
        - content_blocks
    label: Hero with Images Carousel
    description: Hero with Images Carousel
    icon: "bolt"
    tags: ["hero", "images", "carousel"]

# Defines the structure of this component, as well as the default values
blueprint:
    component_id:
    heading: "Making earth cooler for people, nature, climate"
    content_textarea: "Protecting the planet and its natural resources for future generations, by reducing pollution, promoting sustainability, and conserving energy and resources."
    buttons:
        - text: "Get started"
          link: "#"
          is_primary: true
    partners:
        - image:
          alt_text:
    carousel_images:
        - image_path:
          alt_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    buttons:
        type: array
    partners:
        type: array
    carousel_images:
        type: array
