# Metadata about this component, to be used in the CMS
spec:
    structures:
        - content_blocks
    label: Features Image and Icons
    description: Features Image and Icons
    icon: "bolt"
    tags: ["features", "image", "icon"]

# Defines the structure of this component, as well as the default values
blueprint:
    component_id:
    image:
        image_path:
        alt_text:
    heading: "Designed for business teams"
    content_textarea: "Deliver great service experiences fast - without the complexity of	traditional ITSM solutions.Accelerate critical development work, eliminate toil, and deploy changes with ease."
    list:
        - icon_image:
          title:
          description:
          link:
    footer_textarea:

preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    list:
        type: array
