# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: CTA Description Cards
  description: CTA Description Cards
  icon: "bolt"
  tags: ["cta", "cards"]

# Defines the structure of this component, as well as the default values
blueprint:
  component_id:
  heading: "We didn't reinvent the wheel"
  content_html:
  ctas:
    - icon_image:
      text:
      link:

preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  ctas:
    type: array
