# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Content Iframe
  description: Content Iframe
  icon: "bolt"
  tags: ["content", "iframe"]

# Defines the structure of this component, as well as the default values
blueprint:
  component_id:
  heading:
  iframe_textarea: ""
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_highlighted:
    type: switch
