# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: CTA Background
  description: CTA Background
  icon: "bolt"
  tags: ["cta", "background"]

# Defines the structure of this component, as well as the default values
blueprint:
  component_id:
  heading: "We didn't reinvent the wheel"
  description:
  link:
  link_text: "CTA"
  background_image:

preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
