# Metadata about this component, to be used in the CMS
spec:
    structures:
        - content_blocks
    label: Content Text & Image
    description: Content Text Image 2 cols
    icon: "bolt"
    tags: ["content", "text", "image", "2 cols"]

# Defines the structure of this component, as well as the default values
blueprint:
    component_id:
    heading: Heading
    subheading: Subheading
    description_html: Description
    cta:
        link:
        text:
    image:
        image_path:
        alt_text:
        image_position:

preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    image_position:
        type: choice
        options:
            values:
                - left
                - right
