# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Features Comparison Cards
  description: Features Comparison Cards
  icon: "bolt"
  tags: ["features", "comparison", "card"]

# Defines the structure of this component, as well as the default values
blueprint:
  component_id:
  heading: "The most trusted cryptocurrency platform"
  content_html: "Here are a few reasons why you should choose Flowbite"
  cta_link:
  cta_text:
  cards:
    - title:
      link:

preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  cards:
    type: array
