# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Content Text
  description: Content Text
  icon: "bolt"
  tags: ["content", "text"]

# Defines the structure of this component, as well as the default values
blueprint:
  component_id:
  full_content_html: ""
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_highlighted:
    type: switch
