# Metadata about this component, to be used in the CMS
spec:
    structures:
        - content_blocks
    label: Hero Signup
    description: Hero with Signup form
    icon: "bolt"
    tags: ["hero", "signup"]

# Defines the structure of this component, as well as the default values
blueprint:
    component_id:
    heading:
        before_highlighted: A 5-Day email course showing you how to
        highlighted: 10x
        after_highlighted: your website growth in 2024
    footer_html: "Get started now"
    image:
        image_path:
        alt_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
